Lesson 17
vtx123/rdreams_homework pull request #16
Opened 2024-01-16 16:08 UTC by vtx123

2024-01-23 17:37 UTC, helen-black commented on Lesson17/Vector2d.cpp
> +}
check if they aren't equal

2024-01-23 17:38 UTC, helen-black requested changes

2024-01-23 17:38 UTC, helen-black commented on Lesson17/Vector2d.cpp
> +
check if i is nou out of range

2024-01-23 19:08 UTC, vtx123 commented on Lesson17/Vector2d.cpp
> +
smth like this?
float& Vector2d::operator[](int i) {
    if(i <= 0 ) { return _x;} else { return _y}
}

2024-02-09 21:24 UTC, vtx123 commented on Lesson17/Vector2d.cpp
> +}
fixed

2024-02-09 21:25 UTC, merged